scoold.app_name = "ETech Scoold"
scoold.host_url = "http://10.21.2.2:8021"
#scoold.port = 8021
scoold.para_endpoint = "http://para:8080"
scoold.admin = "jrochte@etechgroup.com"

# security
scoold.security.redirect_uri = "http://10.21.2.2:8020"
scoold.security.allow_unverified_emails = true


# system email address
scoold.support_email = "jrochte@etechgroup.com"

scoold.mail.host = "smtp-relay.brevo.com"
scoold.mail.port = 587
scoold.mail.username = "95a8c0001@smtp-brevo.com"
scoold.mail.password = "xsmtpsib-18366704ca522433c707e51779ea9dd6b0edc8f89f5d07a43689e6161c0b4f21-2j9LCaeQ71EXoWXe"
scoold.mail.tls = false
scoold.mail.ssl = false


# enable SMTP debug logging
scoold.mail.debug = true

scoold.emails.welcome_text1 = "You are now part of {0} - a friendly Q&A community..."
scoold.emails.welcome_text2 = "To get started, simply navigate to the "Ask question" page and ask a question..."
scoold.emails.welcome_text3 = "Best, <br>The {0} team<br><br>"